version: 2.1

orbs:
  python: circleci/python@2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          packages:
            - PyGithub
            - python-dotenv
      - run:
          name: Run Auto Commit
          command: |
            python auto_commit.py
          no_output_timeout: 30m

workflows:
  main:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - main
  scheduled:
    triggers:
      - schedule:
          cron: "0 */4 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - build-and-test 