version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            python -m pip install --upgrade pip
            pip install PyGithub python-dotenv
      - run:
          name: Run Auto Commit
          command: |
            python auto_commit.py
          no_output_timeout: 30m

workflows:
  commit-workflow:
    jobs:
      - build-and-test
  scheduled:
    triggers:
      - schedule:
          cron: "0 */4 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - build-and-test 