version: 2.1

jobs:
  auto-commit:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            python -m pip install --upgrade pip
            pip install PyGithub python-dotenv
      - run:
          name: Run Auto Commit
          command: |
            python auto_commit.py
          no_output_timeout: 30m

workflows:
  version: 2
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0 */4 * * *"  # Runs every 4 hours
          filters:
            branches:
              only:
                - main
    jobs:
      - auto-commit 